config/routes.rb
FirehoseAppHbs::Application.routes.draw do

  root 'static_pages#index' 
  resources :pics

end

app/models/pic.rb
class Pic < ActiveRecord::Base
	mount_uploader :image, ImageUploader
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/pics_controller.rb
class PicsController < ApplicationController
	def index

		@pics = Pic.all

	end

	def new

		@pic = Pic.new
	end

	def create
		Pic.create( pics_params )
		redirect_to pics_path
	end


	private

	def pics_params
		params.require(:pic).permit(:title, :subtitle, :message, :image)
	end

end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController

	def index
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pics_helper.rb
module PicsHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>FirehoseAppHbs</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>
    <div class="navbar navbar-inverse">
    <div class="navbar-inner">
    <div class="container">
     
    <!-- .btn-navbar is used as the toggle for collapsed navbar content -->
    <a class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
    <span class="icon-bar"></span>
    <span class="icon-bar"></span>
    <span class="icon-bar"></span>
    </a>
     
    <!-- Be sure to leave the brand out there if you want it shown -->
     
     <%= link_to 'The Fellowship of the Ring', root_path, :class => 'brand' %>
    <!-- Everything you want hidden at 940px or less, place within here -->
    <div class="nav-collapse collapse">
    <!-- .nav, .navbar-search, .navbar-form, etc -->
    	<ul class ="nav">
    		<li>
    			<%= link_to 'See your Allies', pics_path %>
    		</li>
    		<!-- the # is where you put your link!!-->
    		<li>
    			<%= link_to 'Select Your House', new_pic_path %>
    		</li>
    	</ul>
    </div>
     
    </div>
    </div>
    </div>
<%= yield %>

</body>
</html>

app/views/pics/index.html.erb
<% @pics.each_slice (3) do |slice| %>
	<% slice.each do |pic| %>
	<div class='row'>
<div class="smurfy span4 text-center">
		<h1 class="custom-h1">
			House <br/> <%= pic.title %>
		</h1>
		<br/>
		<h2>
		<%= pic.subtitle %>

		</h2>

		<br/>
		<%= image_tag pic.image %>

		<br/>

		<%= pic.message %>

</div>

	<% end %>
<% end %>

app/views/pics/new.html.erb
<div class = "smurfy span4 text-center">
	<h2 class='custom-h2'>Enter your Allegiance</h2>
	<%= simple_form_for @pic do |f| %>
		<%= f.input :title, label: 'Enter your House', placeholder: 'Which of the 7 Kingdoms' %>
		<%= f.input :subtitle, label: 'House Motto'%>

		<%= f.input :message %>
		<%= f.input :image, label: "Upload your crest" %>

		<%= f.submit "Save", :class => 'btn btn-primary' %>
	<% end %>

</div>

app/views/static_pages/index.html.erb
<br/>
<div class="span6 offset0 smurfy text-center">


<h1 class='custom-h1'>
	<br/>
	The White City
</h1>

<br/>

<h2>
	Authority is not Given
</h2>

<br/>
<br/>
<%= link_to 'Valar Morgulis', new_pic_path, :class => 'btn btn-primary' %>

</div>